---
blog_app:
  args:
    store: blog
    url_root: /blog
  class: Statocles::App::Blog
deploy:
  args:
    branch: gh-pages
  class: Statocles::Deploy::Git
page_app:
  args:
    store: page
    url_root: /page
  class: Statocles::App::Basic
site:
  args:
    apps:
      blog:
        $ref: blog_app
      page:
        $ref: page_app
      static:
        $ref: static_app
    base_url: http://alpha6.ru
    deploy:
      $ref: deploy
    index: blog
    nav:
      main:
        - href: /
          title: Blog
    theme:
      $ref: theme
    title: Just another blog
  class: Statocles::Site
  on:
    - build:
        $class: Statocles::Plugin::LinkCheck
        $sub: check_pages
static_app:
  args:
    store: static
    url_root: /static
  class: Statocles::App::Basic
theme:
  args:
    store: theme
  class: Statocles::Theme
